### ISSUE TITLE
GPU and other hardware used?

### ISSUE THREAD

**Issue by MHRosenberg** [alen-smajic/Stable-Diffusion-Latent-Space-Explorer#1]
Hi Alen,

Great work! This is the best I've seen so far!

Forgive me if I missed it but you could you say a bit about what GPU and other hardware was used to run this scripts?

Best,
Matthew

**Comment by alen-smajic** [comment]
Hi Matthew,

sorry for the late response but hope it still helps.
I used a GTX 1080 back then which has 8GB of RAM, it should probably work also with 6GB of RAM.

Best,
Alen
